version: "3.7"
services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/postgresql/dbdata
    ports:
      - 3333:5432
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:8000
    depends_on:
      - db
