version: "3.7"
services:
  db:
    image: postgres:12
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 3333:5432
    healthcheck:
      test: bash -c "pg_isready -U ${POSTGRES_USER}"
      interval: 1s
      timeout: 1s
      retries: 5
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:8000
    depends_on:
      db:
        condition: service_healthy
volumes:
  dbdata:
    external: true
