# Generated by Django 3.2.5 on 2021-07-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PCR', 'PCR'), ('Anticorpos', 'Anticorpos')], max_length=10)),
                ('data_solicitacao', models.DateTimeField(verbose_name='Data de Solicitação')),
                ('data_execucao', models.DateTimeField(verbose_name='Data de Execução')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(verbose_name='Data de Coleta')),
                ('tipo_material', models.CharField(max_length=30)),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep3.paciente')),
            ],
        ),
    ]
